### ISSUE TITLE
주문 배송정보 XE 1.7.12 새주소 반영되지 않는 문제

### ISSUE THREAD

**Issue by treasurej** [nurigo/xe-module-ncart#1]
주문 배송정보 XE 1.7.12 새주소 반영되지 않는 문제

input type="hidden" name="address[]" class="krzip-hidden-postcode" value="135-712"

이렇게 value에는 잘 반영 되는데

화면상 표시되는
input type="text" class="krzip-postcode" value="" disabled="disabled"

이 부분에서는 보이지 않는 문제

**Comment by nurigo-world** [comment]
XE 1.8.1 의 krzip모듈 기준으로 문제를 해결하였습니다.
https://github.com/nurigo/xe-module-ncart/commit/a95858daaf4cfdf5a637afb42898c4b6e4ab7e66
